# Generated by Django 4.0.4 on 2022-07-11 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearOfStudy', models.IntegerField(null=True)),
                ('degree', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classCode', models.CharField(max_length=255)),
                ('className', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('DepartmentName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metriculationNumber', models.CharField(max_length=10, null=True)),
                ('cohort', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam_board_preparation_app.cohort')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1Mark', models.IntegerField()),
                ('q2Mark', models.IntegerField()),
                ('q3Mark', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_board_preparation_app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_board_preparation_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Coursework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradeMark', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_board_preparation_app.course')),
                ('studnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_board_preparation_app.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='exam_board_preparation_app.student'),
        ),
    ]
