# Generated by Django 4.0.4 on 2022-07-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_board_preparation_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classCode', models.CharField(max_length=255)),
                ('className', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matriculation', models.CharField(max_length=7, unique=True)),
                ('degree', models.CharField(max_length=4)),
                ('class1', models.CharField(max_length=255)),
                ('class2', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_name',
            new_name='degree',
        ),
        migrations.RemoveField(
            model_name='student',
            name='metriculation_number',
        ),
    ]
