# Generated by Django 4.0.4 on 2022-07-11 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_board_preparation_app', '0002_cohort_course_csv_rename_student_name_student_degree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradeMark', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1Mark', models.IntegerField()),
                ('q2Mark', models.IntegerField()),
                ('q3Mark', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Csv',
        ),
        migrations.RemoveField(
            model_name='student',
            name='degree',
        ),
        migrations.AddField(
            model_name='cohort',
            name='yearOfStudy',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(to='exam_board_preparation_app.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='cohort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam_board_preparation_app.cohort'),
        ),
        migrations.AddField(
            model_name='student',
            name='metriculationNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='className',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_board_preparation_app.course'),
        ),
        migrations.AddField(
            model_name='exam',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_board_preparation_app.student'),
        ),
        migrations.AddField(
            model_name='coursework',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_board_preparation_app.course'),
        ),
        migrations.AddField(
            model_name='coursework',
            name='studnet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_board_preparation_app.student'),
        ),
    ]
