# Generated by Django 4.0.4 on 2022-07-11 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_board_preparation_app', '0002_rename_id_departments_departmentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departments',
            old_name='DepartmentID',
            new_name='id',
        ),
    ]
