# Generated by Django 4.0.4 on 2022-07-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_board_preparation_app', '0003_coursework_exam_delete_csv_remove_student_degree_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='student',
            new_name='students',
        ),
        migrations.AlterField(
            model_name='student',
            name='metriculationNumber',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
